### ISSUE TITLE
[Ohne Ehre] Kleine Fehlersammlung

### ISSUE THREAD

**Issue by KaiderWeise** [Studio-VTT-Bastler/Studio-VTT-Bastler#1]
**Willkommen**
"exclusiven" -> "exklusiven"
"einbauen ," -> "einbauen,"

**Szene: Eine Dryade in Nöten**
"Im Folgenden die Antworten auf die meisten Fragen der Helden." -> Hier fehlt ein Verb. Der Satz klingt so komisch.

**Szene: Wildschweinrotte**
"Ende: Die Helden schaffen es zu fliehen, die Wildschweine von sich ablenken oder sie alle zu besiegen." -> "...abzulenken..."

**Szene: Flussüberquerung**
"Szene in Foundry: "
"Akteure: "
Bei beiden Angaben steht nichts nach dem Doppelpunkt. Es wirkt, als wurde vergessen hier etwas angzugeben. Ein "-" oder "keine" wäre denke ich besser.

"Schwimmen: (...)Bei Misserfolg verliert der Held 1W3 Gegenstände aus seinem Besitz, vorzugsweise Kleinkram oder Geld."
Ich würde hier auch das 1W3 rollable machen mit [[/r 1d3]] oder direkt mit [[1d3]]. Das spart mir das eventuelle Wechseln auf den Chat und das Nutzen des Moduls DiceTray bzw. manuelles Eingeben im Chat. Einfach ein Mausklick und fertig :)

"Misslingt eine Schwimmen-Probe katastrophal)..." -> Ist damit ein Patzer gemeint oder wann misslingt die Probe katastrophal?

**Szene: Der Fund**
"Akteure: "
Es steht nichts nach dem Doppelpunkt. Es wirkt, als wurde das vergessen. Ein "-" oder "keine" wäre besser.

"Am besten eignet sie sich als "Belohnung" nach dem Spiel mit den Feen in Szene: Der See."
-> "Der See" muss "Der Teich" heißen

**Szene: Der Teich**
"Szene in Foundry: "
"Akteure: "
Bei beiden Angaben steht nichts nach dem Doppelpunkt. Es wirkt, als wurde vergessen hier etwas angzugeben. Ein "-" oder "keine" wäre denke ich besser.

Die Kommunikation bzw. die Antworten der Fee sollten ebenfalls in Kursiv stehen (wie bei der Dryade)

"Tip 1:" und "Tip 2:" -> Muss heißen "Tipp 1:" bzw. "Tipp 2:"

"HeldIn" -> "Held/in"

**Szene: Entscheidung im Räuberversteck**
"QS1", "QS2", usw. sollte fettgedruckt sein (wie beiden vorherigen Szenen auch)

"Plothooks" sollte "Abenteueraufhänger" heißen 

**Weitere Anmerkungen**: 
1. Begegnet man Farline von Schneehag überhaupt in diesem Abenteuer? Ich habe beim ersten Durchlesen nichts gefunden? In der Szene "Entscheidung im Räuberversteck" steht irgendwo "Einer der Räuber wird beim Vorschlag aber verdächtigerweise sagen, dass "der Ritterin das aber nicht gefallen wird". Dies kann die Helden hellhörig werden lassen. Der gesamte Hintergrund wird weiter unten beschrieben." Allerdings kann ich nichts dazu finden. Zudem wundert mich, dass diese NSC mit Werten und allem drum und dran angelegt wurde, wenn man sie doch sowieso nie zu Gesicht bekommt? 
2. Ich hätte mir gewünscht, wenn es bereits einen Anführer-Räuber gäbe, der über die angesprochenen Sonderfertigkeiten bereits verfügt, so dass man sich die Mühe nicht mehr machen muss. Aber das ist Jammern auf hohem Niveau :)

**Comment by Studio-VTT-Bastler** [comment]
Willkommen
- [ ] "exclusiven" -> "exklusiven"
- [ ] "einbauen ," -> "einbauen,"

Szene: Eine Dryade in Nöten
- [ ] "Im Folgenden die Antworten auf die meisten Fragen der Helden." -> Hier fehlt ein Verb. Der Satz klingt so komisch.

Szene: Wildschweinrotte
- [ ] "Ende: Die Helden schaffen es zu fliehen, die Wildschweine von sich ablenken oder sie alle zu besiegen." -> "...abzulenken..."

- [ ] Szene: Flussüberquerung
"Szene in Foundry: "
"Akteure: "
Bei beiden Angaben steht nichts nach dem Doppelpunkt. Es wirkt, als wurde vergessen hier etwas angzugeben. Ein "-" oder "keine" wäre denke ich besser.

- [ ] "Schwimmen: (...)Bei Misserfolg verliert der Held 1W3 Gegenstände aus seinem Besitz, vorzugsweise Kleinkram oder Geld."
Ich würde hier auch das 1W3 rollable machen mit [[/r 1d3]] oder direkt mit [[1d3]]. Das spart mir das eventuelle Wechseln auf den Chat und das Nutzen des Moduls DiceTray bzw. manuelles Eingeben im Chat. Einfach ein Mausklick und fertig :)

- [ ]  "Misslingt eine Schwimmen-Probe katastrophal)..." -> Ist damit ein Patzer gemeint oder wann misslingt die Probe katastrophal?

- [ ] Szene: Der Fund
"Akteure: "
Es steht nichts nach dem Doppelpunkt. Es wirkt, als wurde das vergessen. Ein "-" oder "keine" wäre besser.

- [ ] "Am besten eignet sie sich als "Belohnung" nach dem Spiel mit den Feen in Szene: Der See."
-> "Der See" muss "Der Teich" heißen

- [ ] Szene: Der Teich
"Szene in Foundry: "
"Akteure: "
Bei beiden Angaben steht nichts nach dem Doppelpunkt. Es wirkt, als wurde vergessen hier etwas angzugeben. Ein "-" oder "keine" wäre denke ich besser.

- [ ] Die Kommunikation bzw. die Antworten der Fee sollten ebenfalls in Kursiv stehen (wie bei der Dryade)

- [ ] "Tip 1:" und "Tip 2:" -> Muss heißen "Tipp 1:" bzw. "Tipp 2:"

- [ ] "HeldIn" -> "Held/in"

- [ ] Szene: Entscheidung im Räuberversteck

- [ ] "QS1", "QS2", usw. sollte fettgedruckt sein (wie beiden vorherigen Szenen auch)

- [ ] "Plothooks" sollte "Abenteueraufhänger" heißen

Weitere Anmerkungen:
1. Begegnet man Farline von Schneehag überhaupt in diesem Abenteuer? Ich habe beim ersten Durchlesen nichts gefunden? In der Szene "Entscheidung im Räuberversteck" steht irgendwo "Einer der Räuber wird beim Vorschlag aber verdächtigerweise sagen, dass "der Ritterin das aber nicht gefallen wird". Dies kann die Helden hellhörig werden lassen. Der gesamte Hintergrund wird weiter unten beschrieben." Allerdings kann ich nichts dazu finden. Zudem wundert mich, dass diese NSC mit Werten und allem drum und dran angelegt wurde, wenn man sie doch sowieso nie zu Gesicht bekommt?
2. Ich hätte mir gewünscht, wenn es bereits einen Anführer-Räuber gäbe, der über die angesprochenen Sonderfertigkeiten bereits verfügt, so dass man sich die Mühe nicht mehr machen muss. Aber das ist Jammern auf hohem Niveau :)
